name: Build iOS App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js (>=20.0.0)
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build web assets
        run: npm run build    # Gerar os arquivos web na pasta www

      - name: Install Capacitor & CocoaPods
        run: npm install -g @capacitor/cli && npx cap sync ios

      - name: Build iOS App
        run: |
          cd ios/App
          pod install
          xcodebuild -workspace App.xcworkspace -scheme App -sdk iphoneos -configuration Release archive -archivePath App.xcarchive
